### ISSUE TITLE
Organisation notifme

### ISSUE THREAD

**Issue by BDav24** [NotifMe/NotifMe#1]
Bonjour,

Je vois que vous n'utilisez plus l'organisation "notifme". Serait-il possible de récupérer le nom pour un projet ?

Bonne journée,
David

**Comment by Louishancquart** [comment]
Bonjour,
Je ne vois pas d'inconvenient à cela.

Bonne journée à toi aussi.
Louis

**Comment by BDav24** [comment]
@Louishancquart Comment peut-on procéder ? Tu supprimes l'organisation et j'en recrée une nouvelle ?

Merci,
David

**Comment by Louishancquart** [comment]
np ;)

**Comment by Louishancquart** [comment]
j'ai quitté le projet. Je suppose que c'est bon à moins que ce soit mon collègue ( Alexis Cappelli ) qui avait créé le projet. Auquel cas il faut lui demander.

Bon courage
Louis

**Comment by BDav24** [comment]
Le compte a toujours l'air d'être là, est-ce que tu saurais comment je peux contacter ton collègue (ou lui transmettre l'info) ?

A priori il faut faire l'une des deux démarches :
https://help.github.com/articles/changing-your-github-username/
https://help.github.com/articles/deleting-your-user-account/

Merci,
David

**Comment by BDav24** [comment]
@Alexiscap ?

**Comment by Louishancquart** [comment]
oui c'est ca.

**Comment by Alexiscap** [comment]
Hello,

Avec la mention j'ai pu voir le fil :).
Pas de soucis pour libérer le compte, on ne s'en sert absolument plus.

Je fais la suppression de ce pas.

A+

**Comment by Alexiscap** [comment]
Mince, à @Louishancquart, tu te rappelles des accès pour le compte Notifme ? Je pensais qu'il était hébergé sur mon utilisateur Git mais en fait non .. Je me souviens qu'on avait créé une gmail, mais je n'ai à prioris plus les accès.
